<a href="https://colab.research.google.com/github/PvrpleJade/AIDA-2/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Types of Matrices

In [7]:
import numpy as np
### According to Shape
row = np.array([
                [4,2,9]
])

col = np.array([
                [9],
                [1],
                [2]
])

square = np.array([
                   [1,2],
                   [3,2]
])

def vect_to_row(vect):
  size = vect.size
  row = vect.reshape(1,size)
  return row
vectA = np.array([1,2,3,4,5])
vectB = np.array([1,2,3,4,5,6,7,8])
vectC = np.array([1,2,3,4,5,6,7,8,9,10])



In [8]:
print (col)
print (square)
vect_to_row(vectC)

[[9]
 [1]
 [2]]
[[1 2]
 [3 2]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [13]:
### According to Values
zeros = np.zeros((2,3))
zeros

ones = np.ones((2,3))
ones

full = np.full((2,3),5)
full

v = np.array([1,2,3])
diagonal =np.diag(v)
diagonal

I = np.eye(3)
I = np.identity(4)
I

s = 3
I = np.identity(4)

scalar = s*I
scalar



array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [19]:
print (zeros)
print (ones)
print (full)
print (diagonal)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [23]:
def scalar_matrix(n,scalar):

  scalar_matrix = np.identity(n)*scalar
  return scalar_matrix

scalar_matrix(10,145)

array([[145.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 145.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 145.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 145.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 145.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 145.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 145.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 145.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 145.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 145.]])

# Matrix Operation
### Arithmetic in Matrices

In [26]:
import numpy as np

A = 2*np.ones((2,2))
2 + A
2*A
A**2 
A

array([[2., 2.],
       [2., 2.]])

### Dot Product

In [27]:
B = np.array([
              [1,2],
              [3,7]
])

B.dot(B)

array([[ 7, 16],
       [24, 55]])

### Transposition

In [29]:
import numpy as np

rowB = np.array([[1,2,3]])
rowB.T

matA = np.array([
                 [1,4],
                 [3,7]
])
matA.T

matB = np.array([
                 [1,2,3],
                 [3,7,4],
                 [-1,0,1]
])

matB.T

array([[ 1,  3, -1],
       [ 2,  7,  0],
       [ 3,  4,  1]])

In [30]:
matA.T

array([[1, 3],
       [2, 7]])

###Determinants

In [31]:
A = np.array([
              [1,2],
              [2,4]
])

B = np.array([
              [1,2,3],
              [1,3,3],
              [5,1,15]
])

np.linalg.det(B)

0.0

###Singular Matrices/Vectors

In [32]:
### Rank 0 matrices
s = np.array(1)
s.ndim

0

In [33]:
### Rank 1 Matrices

v = np.array([1,2,3])
v.ndim

1

In [34]:
### Rank 2 Matrices

A = np.array([
              [1,2,3],
              [2,3,1],
              [1,0,1]
])
A.ndim

2

In [36]:
X = np.array([
              [1,2,3],
              [2,3,1],
              [1,0,1]
])

X.shape # (3, 3)

(3, 3)

In [39]:
X = np.array([
              [
                [1,2,3],
                [2,3,1],
                [1,0,1]],
              [
                [1,2,3],
                [2,3,1],
                [1,0,1]]
])
X.ndim 
X.shape

(2, 3, 3)

In [40]:
B = np.array([
              [1,2,3],
              [2,4,6],
              [1,3,4]
])
np.linalg.det(B)

0.0